runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  # Set your Laravel application key
  APP_KEY: YOUR_APP_KEY

  # Set your database connection details
  DB_CONNECTION: mysql
  DB_HOST: YOUR_DB_HOST
  DB_DATABASE: YOUR_DB_NAME
  DB_USERNAME: YOUR_DB_USERNAME
  DB_PASSWORD: YOUR_DB_PASSWORD

  # Set other Laravel environment variables as needed

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Uncomment the following lines if you are using a custom domain
# handlers:
# - url: /.*
#   script: auto

# Uncomment the following lines if you want to enable HTTPS
# - url: /.*
#   script: auto
#   secure: always